import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/signup")({
  head: () => ({ meta: [{ title: "Get Started | BuildTrack" }, { name: "description", content: "Create a BuildTrack workspace for your construction projects." }, { property: "og:title", content: "Get Started | BuildTrack" }, { property: "og:description", content: "Bring your construction projects, teams, and buyers together." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: SignupPage,
});

function SignupPage() { return <main className="grid min-h-screen lg:grid-cols-2"><section className="blueprint-grid hidden bg-surface-dark p-12 text-primary-foreground lg:flex lg:flex-col lg:justify-between"><Link to="/" className="inline-flex items-center gap-2 text-sm text-primary-foreground/70 hover:text-primary-foreground"><ArrowLeft className="size-4"/> BuildTrack</Link><div><p className="text-xs font-bold uppercase text-primary">Your shared project record</p><h1 className="mt-4 max-w-xl text-5xl font-semibold">Bring every project update into one clear view.</h1><ul className="mt-10 space-y-4">{["Connect office and site teams","Keep buyers informed","Track work through possession"].map(x=><li key={x} className="flex gap-3 text-primary-foreground/75"><Check className="text-primary"/>{x}</li>)}</ul></div><p className="text-xs text-primary-foreground/40">Construction management, built for real projects.</p></section><section className="flex items-center justify-center bg-background p-5 md:p-12"><div className="w-full max-w-md"><Link to="/" className="mb-10 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground lg:hidden"><ArrowLeft className="size-4"/> Back to BuildTrack</Link><p className="text-xs font-bold uppercase text-primary">Create workspace</p><h2 className="mt-3 font-display text-3xl font-semibold">Start with your company</h2><form className="mt-8 space-y-5"><label className="block text-sm font-medium">Full name<input className="mt-2 h-12 w-full border border-input bg-card px-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="Your name"/></label><label className="block text-sm font-medium">Company name<input className="mt-2 h-12 w-full border border-input bg-card px-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="Construction company"/></label><label className="block text-sm font-medium">Work email<input type="email" className="mt-2 h-12 w-full border border-input bg-card px-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="you@company.com"/></label><Button type="submit" variant="construction" size="lg" className="w-full">Create Workspace</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">Already have an account? <Link to="/login" className="font-semibold text-primary hover:underline">Sign in</Link></p></div></section></main> }